In [ ]:
#how to plot
import numpy as np
import matplotlib.pyplot as plt
from sympy import symbols

x = np.linspace(0, 2, 100)  # Sample data.
plt.figure(figsize=(5, 2.7), layout='constrained')
plt.plot(x, x, label='linear')  # Plot some data on the (implicit) Axes.
plt.plot(x, x**2, label='quadratic')  # etc.
plt.plot(x, x**3, label='cubic')
plt.xlabel('x label')
plt.ylabel('y label')
plt.title("Simple Plot")
plt.legend()

In [2]:
#how to show sympy symbols
import numpy as np
from sympy import symbols, diff, integrate, solve, sin, exp, cos, oo, Eq, Function, dsolve, Matrix, pi, Integral, latex, limit
from IPython.display import display, Math

# Defining symbols
x, t, z, nu = symbols('x t z nu')
x, y = symbols('x y')

# Simple expression
expr = x + 2*y


# Differentiation using sympy's diff, not numpy's np.diff
d1 = diff(sin(x)*exp(x), x)


# Integration
I1 = integrate(exp(x)*sin(x) + exp(x)*cos(x), x)

# Definite integration
I2 = integrate(sin(x**2), (x, -oo, oo))

# Solving an equation
x1 = solve(x**2 - 2, x)

# Limit calculation
A1 = limit(sin(x)/x, x, 0)
print("Limit of sin(x)/x as x approaches 0:", A1)

# Differential equation solving
y = Function('y')
y1 = dsolve(Eq(y(t).diff(t, t) - y(t), exp(t)), y(t))
print("Solution of the differential equation:", y1)
display(Math(latex(y1)))

# Eigenvalues of a matrix
egn1 = Matrix([[1, 2], [2, 2]]).eigenvals()
print("Eigenvalues of the matrix:", egn1)
display(Math(latex(egn1)))

# Latex representation of an integral
o1 = latex(Integral(cos(x)**2, (x, 0, pi)))
print("Latex representation of the integral:", o1)
display(Math(o1))

Limit of sin(x)/x as x approaches 0: 1
Solution of the differential equation: Eq(y(t), C2*exp(-t) + (C1 + t/2)*exp(t))


<IPython.core.display.Math object>

Eigenvalues of the matrix: {3/2 - sqrt(17)/2: 1, 3/2 + sqrt(17)/2: 1}


<IPython.core.display.Math object>

Latex representation of the integral: \int\limits_{0}^{\pi} \cos^{2}{\left(x \right)}\, dx


<IPython.core.display.Math object>

In [1]:
#array arranging
import numpy as np

a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))
b = np.array([6, 7, 8])
type(b)
print(np.zeros((3, 4)))
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A.dot(B))
a = np.array([2, 3, 4, 5])
b = np.array([8, 5, 4])
c = np.array([5, 4, 6, 8, 3])
ax, bx, cx = np.ix_(a, b, c)
print(ax)
x = np.arange(0, 10, 2)
y = np.arange(5)
m = np.vstack([x, y])
print(m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 4]
 [3 4]]
[[[2]]

 [[3]]

 [[4]]

 [[5]]]
[[0 2 4 6 8]
 [0 1 2 3 4]]


In [ ]:
#plot histogram
import numpy as np
import matplotlib.pyplot as plt

rg = np.random.default_rng(1)

# Build a vector of 10000 normal deviates with variance 0.5^2 and mean 2
mu, sigma = 2, 0.5
v = rg.normal(mu, sigma, 10000)

# Plot a normalized histogram with 50 bins
plt.hist(v, bins=50, density=True)       
#matplotlib version (plot)

# Compute the histogram with numpy and then plot it
(n, bins) = np.histogram(v, bins=50, density=True)  
# NumPy version (no plot)
plt.plot(.5 * (bins[1:] + bins[:-1]), n)

In [ ]:
#gaussian quadrature
from scipy.integrate import quad

def integrand(x, a, b):
    return a*x**2 + b

a = 2
b = 1
I = quad(integrand, 0, 1, args=(a,b))
print(I)

In [3]:
import numpy as np
from numpy import linalg as LA
from numpy.linalg import inv

def compute_vector_norms(a):
    """
    Computes the norms of a vector.
    
    Parameters:
    a (numpy.ndarray): The input vector.
    
    Returns:
    tuple: 2-norm, 1-norm, and infinity norm of the vector.
    """
    anm2 = LA.norm(a)          # 2-norm (Euclidean norm)
    anm1 = LA.norm(a, 1)       # 1-norm (sum of absolute values)
    anminf = LA.norm(a, np.inf) # Infinity norm (maximum absolute value)
    
    return anm2, anm1, anminf

def compute_matrix_norms(A):
    """
    Computes the norms of a matrix.
    
    Parameters:
    A (numpy.ndarray): The input matrix.
    
    Returns:
    tuple: 2-norm, 1-norm, and infinity norm of the matrix.
    """
    Anm2 = LA.norm(A)          # 2-norm of the matrix
    Anm1 = LA.norm(A, 1)       # 1-norm of the matrix
    Anminf = LA.norm(A, np.inf) # Infinity norm of the matrix
    
    return Anm2, Anm1, Anminf

def compute_matrix_inverse(A):
    """
    Computes the inverse of a matrix.
    
    Parameters:
    A (numpy.ndarray): The input matrix.
    
    Returns:
    numpy.ndarray: The inverse of the matrix.
    """
    Ainv = inv(A)
    return Ainv

def compute_condition_number(A):
    """
    Computes the condition number of a matrix using the 2-norm.
    
    Parameters:
    A (numpy.ndarray): The input matrix.
    
    Returns:
    float: The condition number of the matrix.
    """
    Anm2 = LA.norm(A)           # 2-norm of the matrix
    Ainv = inv(A)               # Inverse of the matrix
    Ainvnm2 = LA.norm(Ainv)     # 2-norm of the inverse
    
    condA = Anm2 * Ainvnm2      # Condition number
    return condA

def compute_determinant(A):
    """
    Computes the determinant of a matrix.
    
    Parameters:
    A (numpy.ndarray): The input matrix.
    
    Returns:
    float: The determinant of the matrix.
    """
    dA = np.linalg.det(A)
    return dA

# Example usage:
# Define a vector and a matrix
a = np.array([4, 4, -4, 4])
A = np.array([[1.0, 1.0/2.0, 1.0/3.0, 1.0/4.0, 1.0/5.0],
              [1.0/2.0, 1.0/3.0, 1.0/4.0, 1.0/5.0, 1.0/6.0],
              [1.0/3.0, 1.0/4.0, 1.0/5.0, 1.0/6.0, 1.0/7.0],
              [1.0/4.0, 1.0/5.0, 1.0/6.0, 1.0/7.0, 1.0/8.0],
              [1.0/5.0, 1.0/6.0, 1.0/7.0, 1.0/8.0, 1.0/9.0]])

# Compute and print vector norms
vector_norms = compute_vector_norms(a)
print("Vector Norms (2-norm, 1-norm, Infinity norm):", vector_norms)

# Compute and print matrix norms
matrix_norms = compute_matrix_norms(A)
print("Matrix Norms (2-norm, 1-norm, Infinity norm):", matrix_norms)

# Compute and print the inverse of the matrix
A_inv = compute_matrix_inverse(A)
print("Inverse of matrix A:\n", A_inv)

# Compute and print the condition number of the matrix
condition_number = compute_condition_number(A)
print("Condition number of matrix A:", condition_number)

# Compute and print the determinant of the matrix
determinant = compute_determinant(A)
print("Determinant of matrix A:", determinant)

Vector Norms (2-norm, 1-norm, Infinity norm): (8.0, 16.0, 4.0)
Matrix Norms (2-norm, 1-norm, Infinity norm): (1.5809062632720225, 2.283333333333333, 2.283333333333333)
Inverse of matrix A:
 [[ 2.500e+01 -3.000e+02  1.050e+03 -1.400e+03  6.300e+02]
 [-3.000e+02  4.800e+03 -1.890e+04  2.688e+04 -1.260e+04]
 [ 1.050e+03 -1.890e+04  7.938e+04 -1.176e+05  5.670e+04]
 [-1.400e+03  2.688e+04 -1.176e+05  1.792e+05 -8.820e+04]
 [ 6.300e+02 -1.260e+04  5.670e+04 -8.820e+04  4.410e+04]]
Condition number of matrix A: 480849.1169945075
Determinant of matrix A: 3.749295132516573e-12


In [1]:
from sympy.matrices import Matrix, MatrixSymbol, BlockMatrix
from scipy.linalg import block_diag
import numpy as np
from numpy.linalg import inv
from sympy import symbols

# Define symbolic variables
m, n = symbols('m n')

# Define symbolic matrices
A = MatrixSymbol('A', n, n)  # Square matrix A
B = MatrixSymbol('B', n, m)  # Matrix B
C = MatrixSymbol('C', m, n)  # Matrix C
D = MatrixSymbol('D', m, m)  # Square matrix D

def create_block_matrix(A, B, C, D):
    """
    Create a block matrix from four matrices.
    
    Parameters:
    A (MatrixSymbol): Top-left matrix.
    B (MatrixSymbol): Top-right matrix.
    C (MatrixSymbol): Bottom-left matrix.
    D (MatrixSymbol): Bottom-right matrix.
    
    Returns:
    BlockMatrix: The resulting block matrix.
    """
    X = BlockMatrix([[A, B], [C, D]])
    return X

# Create the block matrix X
X = create_block_matrix(A, B, C, D)
print("Block Matrix X:\n", X)

def schur_decomposition(X, matrix_name='A'):
    """
    Perform Schur decomposition of a block matrix.
    
    Parameters:
    X (BlockMatrix): The block matrix to decompose.
    matrix_name (str): The name of the matrix to keep invertible.
    
    Returns:
    BlockMatrix: The Schur decomposition of the block matrix.
    """
    X_schur = X.schur(matrix_name)
    return X_schur

# Perform Schur decomposition, keeping matrix A invertible
X1 = schur_decomposition(X, 'A')
print("Schur Decomposition of Block Matrix X:\n", X1)

def lu_decomposition(X):
    """
    Perform LDU decomposition of a block matrix.
    
    Parameters:
    X (BlockMatrix): The block matrix to decompose.
    
    Returns:
    tuple: Lower triangular matrix L, diagonal matrix D, and upper triangular matrix U.
    """
    L, D, U = X.LDUdecomposition()
    return L, D, U

# Perform LDU decomposition of the block matrix
L1, D1, U1 = lu_decomposition(X)
print("Lower Triangular Matrix L:\n", L1)
print("Diagonal Matrix D:\n", D1)
print("Upper Triangular Matrix U:\n", U1)

def convert_to_full_matrix(block_matrix):
    FM=block_diag(block_matrix)
    matrixFM=np.matrix(FM.reshape(4,4))
    full_matrix=np.array(matrixFM).astype(np.float64)
    return full_matrix


# Convert L, D, U to full matrices
full_L = convert_to_full_matrix(L1)
full_D = convert_to_full_matrix(D1)
full_U = convert_to_full_matrix(U1)

print("Full Matrix L:\n", full_L)
print("Full Matrix D:\n", full_D)
print("Full Matrix U:\n", full_U)

def matrix_inverses(L, D, U):
    """
    Compute the inverses of matrices L, D, and U.
    
    Parameters:
    L (np.ndarray): Lower triangular matrix.
    D (np.ndarray): Diagonal matrix.
    U (np.ndarray): Upper triangular matrix.
    
    Returns:
    tuple: Inverses of L, D, and U.
    """
    L_inv = inv(L)
    D_inv = inv(D)
    U_inv = inv(U)
    return L_inv, D_inv, U_inv

# Compute inverses of L, D, U
L_inv, D_inv, U_inv = matrix_inverses(full_L, full_D, full_U)
print("Inverse of Lower Triangular Matrix L:\n", L_inv)
print("Inverse of Diagonal Matrix D:\n", D_inv)
print("Inverse of Upper Triangular Matrix U:\n", U_inv)

def reconstruct_matrix(U_inv, D_inv, L_inv):
    """
    Reconstruct the original matrix using the inverses of L, D, and U.
    
    Parameters:
    U_inv (np.ndarray): Inverse of the upper triangular matrix.
    D_inv (np.ndarray): Inverse of the diagonal matrix.
    L_inv (np.ndarray): Inverse of the lower triangular matrix.
    
    Returns:
    np.ndarray: Reconstructed matrix.
    """
    mmDinvLinv = np.dot(D_inv, L_inv)
    reconstructed_matrix = np.dot(U_inv, mmDinvLinv)
    return reconstructed_matrix

# Reconstruct the original matrix
reconstructed = reconstruct_matrix(U_inv, D_inv, L_inv)
print("Reconstructed Matrix:\n", reconstructed)

Block Matrix X:
 Matrix([
[A, B],
[C, D]])
Schur Decomposition of Block Matrix X:
 -C*A**(-1)*B + D
Lower Triangular Matrix L:
 Matrix([
[        I, 0],
[C*A**(-1), I]])
Diagonal Matrix D:
 Matrix([
[A,                0],
[0, -C*A**(-1)*B + D]])
Upper Triangular Matrix U:
 Matrix([
[I, A**(-1)*B],
[0,         I]])


TypeError: 'Add' object cannot be interpreted as an integer